data_path: 'C:\Users\reich\Matlab\SimNIBS-4.1\simnibs4_examples\m2m_ernie\' # the folder with either a) t1 & t2 images, or b) t1 image and the segmentation results, e.g., Ernie subject from SimNIBS
simnibs_bin_path: 'C:\Users\reich\Matlab\SimNIBS-4.1\bin\'

t1_path_template: T1.nii.gz # path to T1 relative to data_path; all string substitutions will be done using subject_id
t2_path_template: T2_reg.nii.gz # path to T2 relative to data_path; all string substitutions will be done using subject_id

transducer: 
  n_elements: 10 # number of elements in the transducer
  Elements_ID_mm: [10, 22.3, 30, 36.3, 41.7, 46.5, 51, 55.1, 58.9, 62.5]
  Elements_OD_mm: [21.3, 29.1, 35.3, 40.7, 45.6, 50, 54.1, 58, 61.6, 65]
  curv_radius_mm: 75 # radius of curvature of the bowl 
  dist_to_plane_mm: 67.5 # distance to the transducer plane from the geometric focus
  source_amp: 183573 # [Pa]
  source_phase_deg: [0, 360, 17, 39, 43, 29, 68, 23, 150, 26] # source phase [deg]
  source_freq_hz: 300e3 # [Hz] the central frequency
  pos_t1_grid: [128, 139, 15] # position on T1 grid 

focus_pos_t1_grid: [128, 142, 75] # stimulation target on T1 grid

default_grid_dims: [144, 144, 256]

thermal:
  duty_cycle: 0.5 # share of the stimulation duration during which the stimulation is on
  sim_time_steps: 0.1 # [s] simulation time steps during the stimulation period
  temp_0: 37 #[deg C] initial temperature, currently not used
  stim_duration: 0.6 # [s] stimulation duration within a trial
  iti: 1.2 # interval between the trials, from the start of one trial to the start of another [s]
  n_trials: 12 # number of trials to simulate; the total simulated duration is then n_trials*iti seconds



# Select which k-Wave code to run (see 'run_simulations' for more documentation)
#   MATLAB CPU code 'matlab_cpu'
#   MATLAB GPU code 'matlab_gpu'
#   C++ code (Interactive) 'cpp_interactive'
#   C++ code (Non-Interactive) 'cpp_noninteractive'
#   CUDA code 'cuda' (currently does not work at the Donders HPC, but 'matlab_gpu' works)
code_type: matlab_cpu

# An optional path to LD_LIBRARY used during SimNIBS installation
# If you experience an `undefined symbol` error in `create_mesh_surf.cpython-39-x86_64-linux-gnu.so`, set the next line to your LD_LIBRARY location
ld_library_path: 'C:\Users\reich\Matlab\SimNIBS-4.1\simnibs_env\Scripts\'

# Segmentation software (current options are 'headreco' and 'charm')
segmentation_software: charm.cmd